import = ["~/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/fish"
args = ['-l', '-c', "tmux attach || tmux"]

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"